apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: packetcapture
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: packetcapture
  template:
    metadata:
      labels:
        app: packetcapture
    spec:
      serviceAccountName: packetcapture
      containers:
      - name: controller
        image: packetcapture:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        volumeMounts:
        - name: capture
          mountPath: /capture
      volumes:
      - name: capture
        emptyDir: {}
